:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - course
  - campu
  - notice
  - notice5
  - notice1
  - notice2
  - notice3
  - notice4
